site_name: Coding Test - Reserva de Salas de Reunião
site_url: https://room-scheduling.herokuapp.com/
repo_url: https://github.com/cesarbruschetta/room-scheduling
repo_name: 'GitHub'
theme: readthedocs

nav:
- Home: 'index.md'
- Install: 'setup.md'
- API: 'api.md' 
- Tests: 'tests.md'
- About: 'about.md'

use_directory_urls: false
site_dir: doc_site
