# Generated by Django 2.1.4 on 2018-12-24 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('1', 'Criação'), ('2', 'Edição'), ('3', 'Exclução')], default='1', max_length=2, verbose_name='Status')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Log de Ações',
                'verbose_name_plural': 'Logs de Ações',
            },
        ),
    ]
